# Generated by Django 5.0.4 on 2024-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_user_email_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
