# Generated by Django 5.0.4 on 2024-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='profileid',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
