# Generated by Django 5.0.4 on 2024-05-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('messenger', '0010_rename_user_userr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userr',
            new_name='User',
        ),
    ]
