# Generated by Django 5.0.4 on 2024-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_rename_userr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
