# Generated by Django 5.0.4 on 2024-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_userprofile_picture_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='defaultpp.jpg', upload_to=''),
        ),
    ]
