# Generated by Django 5.0.4 on 2024-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='NUll', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='NUll', max_length=20),
        ),
    ]
